<?php

/*
 * Author: https://github.com/MRokas
 * Version: 0.1
 * Description: smart ?bosschallenge for Shocky. 
 *              No more copper shortsword against Moon Lord, on Last Prism against Eater of the Worlds.
*/

$BOSS_LIST = array(
  "1" => array(
    "King Slime",
    "Eye of Cthulhu",
    "Eater of the World",
    "Brain of Cthulhu",
    "Queen Bee"
  ),
  "2" => array(
    "Skeletron",
    "Wall of Flesh",
  ),
  "3" => array(
    "The Destroyer",
    "The Twins",
    "Skeletron Prime"
  ),
  "4" => array(
    "Plantera",
    "Golem",
  ),
  "5" => array(
    "Duke Fishron"
  ),
  "6" => array(
    "Lunatic Cultist",
    "Vortex Pillar",
    "Nebula Pillar",
    "Solar Pillar",
    "Stardust Pillar",
    "Moon Lord"
  )
);
$WEAPON_LIST = array(
	"0" => array(
		"Yellow Phasesaber",
		"White Phasesaber",
		"Purple Phasesaber",
		"Green Phasesaber",
		"Red Phasesaber",
		"Blue Phasesaber",
		"Demon Bow",
		"War Axe of the Night",
		"Light's Bane",
		"Enchanted Boomerang",
		"Vilethorn",
		"Starfury",
		"Flintlock Pistol",
		"Musket",
		"Minishark",
		"Iron Bow",
		"Nightmare Pickaxe",
		"The Breaker",
		"Flower of Fire",
		"Magic Missile",
		"Flamarang",
		"Molten Fury",
		"Fiery Greatsword",
		"Molten Pickaxe",
		"Space Gun",
		"Muramasa",
		"Aqua Scepter",
		"Harpoon",
		"Ball O' Hurt",
		"Blue Moon",
		"Handgun",
		"Water Bolt",
		"Blade of Grass",
		"Thorn Chakram",
		"Wooden Hammer",
		"Star Cannon",
		"Blue Phaseblade",
		"Red Phaseblade",
		"Green Phaseblade",
		"Purple Phaseblade",
		"White Phaseblade",
		"Yellow Phaseblade",
		"Meteor Hamaxe",
		"Staff of Regrowth",
		"Molten Hamaxe",
		"Flamelash",
		"Phoenix Blaster",
		"Sunfury",
		"Sandgun",
		"Demon Scythe",
		"Night's Edge",
		"Dark Lance",
		"Trident",
		"Pwnhammer",
		"Excalibur",
		"Cobalt Chainsaw",
		"Mythril Chainsaw",
		"Cobalt Drill",
		"Mythril Drill",
		"Adamantite Chainsaw",
		"Adamantite Drill",
		"Dao of Pow",
		"Mythril Halberd",
		"Adamantite Glaive",
		"Breaker Blade",
		"Clockwork Assault Rifle",
		"Cobalt Repeater",
		"Mythril Repeater",
		"Adamantite Repeater",
		"Adamantite Sword",
		"Cobalt Sword",
		"Mythril Sword",
		"Magical Harp",
		"Rainbow Rod",
		"Ice Rod",
		"Flamethrower",
		"Laser Rifle",
		"Magic Dagger",
		"Crystal Storm",
		"Cursed Flames",
		"Megashark",
		"Shotgun",
		"Cobalt Naginata",
		"Gungnir",
		"Light Disc",
		"Hallowed Repeater",
		"Drax",
		"Ice Boomerang",
		"Keybrand",
		"Cutlass",
		"True Excalibur",
		"True Night's Edge",
		"Frostbrand",
		"Tactical Shotgun",
		"Marrow",
		"Unholy Trident",
		"Beam Sword",
		"Ice Blade",
		"Ice Bow",
		"Frost Staff",
		"Amethyst Staff",
		"Topaz Staff",
		"Sapphire Staff",
		"Emerald Staff",
		"Ruby Staff",
		"Diamond Staff",
		"Mushroom Spear",
		"Terra Blade",
		"Grenade Launcher",
		"Rocket Launcher",
		"Proximity Mine Launcher",
		"Cobalt Pickaxe",
		"Mythril Pickaxe",
		"Adamantite Pickaxe",
		"Hammush",
		"Nettle Burst",
		"Blood Butcherer",
		"Tendon Bow",
		"Flesh Grinder",
		"Deathbringer Pickaxe",
		"Blood Lust Cluster",
		"The Undertaker",
		"The Meatball",
		"The Rotted Fork",
		"Flare Gun",
		"Boomstick",
		"Blowgun",
		"Enchanted Sword",
		"Pickaxe Axe",
		"Cobalt Waraxe",
		"Mythril Waraxe",
		"Adamantite Waraxe",
		"Bee Gun",
		"Possessed Hatchet",
		"Bee Keeper",
		"Wasp Gun",
		"Piranha Gun",
		"Pygmy Staff",
		"Bone Sword",
		"Leaf Blower",
		"Palladium Sword",
		"Palladium Pike",
		"Palladium Repeater",
		"Palladium Pickaxe",
		"Palladium Drill",
		"Palladium Chainsaw",
		"Orichalcum Sword",
		"Orichalcum Halberd",
		"Orichalcum Repeater",
		"Orichalcum Pickaxe",
		"Orichalcum Drill",
		"Orichalcum Chainsaw",
		"Titanium Sword",
		"Titanium Trident",
		"Titanium Repeater",
		"Titanium Pickaxe",
		"Titanium Drill",
		"Titanium Chainsaw",
		"Palladium Waraxe",
		"Orichalcum Waraxe",
		"Titanium Waraxe",
		"Chlorophyte Claymore",
		"Chlorophyte Saber",
		"Chlorophyte Partisan",
		"Chlorophyte Shotbow",
		"Chlorophyte Pickaxe",
		"Chlorophyte Drill",
		"Chlorophyte Chainsaw",
		"Chlorophyte Greataxe",
		"Chlorophyte Warhammer",
		"Nimbus Rod",
		"Sniper Rifle",
		"Venus Magnum",
		"Crimson Rod",
		"Stynger",
		"Flower Pow",
		"Rainbow Gun",
		"Chlorophyte Jackhammer",
		"Flower of Frost",
		"Uzi",
		"Magnet Sphere",
		"Picksaw",
		"Heat Ray",
		"Staff of Earth",
		"Golem Fist",
		"Zombie Arm",
		"The Axe",
		"Ice Sickle",
		"Poison Staff",
		"Slime Staff",
		"Book of Skulls",
		"KO Cannon",
		"Snowball Cannon",
		"Bone Pickaxe",
		"Bananarang",
		"Chain Knife",
		"Death Sickle",
		"Golden Shower",
		"Shadowbeam Staff",
		"Inferno Fork",
		"Spectre Staff",
		"Spectre Pickaxe",
		"Spectre Hamaxe",
		"Paladin's Hammer",
		"S.D.M.G.",
		"Vampire Knives",
		"Scourge of the Corruptor",
		"Staff of the Frost Hydra",
		"Candy Corn Rifle",
		"Jack 'O Lantern Launcher",
		"Sickle",
		"Bat Scepter",
		"Raven Staff",
		"Bloody Machete",
		"The Horseman's Blade",
		"Bladed Glove",
		"Stake Launcher",
		"Red Ryder",
		"Candy Cane Sword",
		"Elf Melter",
		"Candy Cane Pickaxe",
		"Fruitcake Chakram",
		"Christmas Tree Sword",
		"Chain Gun",
		"Razorpine",
		"Blizzard Staff",
		"Snowman Cannon",
		"North Pole",
		"Shroomite Digging Claw",
		"Venom Staff",
		"Pulse Bow",
		"Revolver",
		"Gatligator",
		"Katana",
		"Rockfish",
		"Purple Clubberfish",
		"Obsidian Swordfish",
		"Swordfish",
		"Reaver Shark",
		"Sawtooth Shark",
		"Hornet Staff",
		"Imp Staff",
		"Queen Spider Staff",
		"Anchor",
		"Optic Staff",
		"Spider Staff",
		"Pirate Staff",
		"Sticky Grenade",
		"Molotov Cocktail",
		"Falcon Blade",
		"Flairon",
		"Tempest Staff",
		"Razorblade Typhoon",
		"Bubble Gun",
		"Tsunami",
		"Boreal Wood Sword",
		"Boreal Wood Hammer",
		"Boreal Wood Bow",
		"Xeno Staff",
		"Meteor Staff",
		"Vortex Pickaxe",
		"Nebula Pickaxe",
		"Solar Flare Pickaxe",
		"Laser Machinegun",
		"Electrosphere Launcher",
		"Xenopopper",
		"Laser Drill",
		"Influx Waver",
		"Charged Blaster Cannon",
		"The Bee's Knees",
		"Life Drain",
		"Dart Pistol",
		"Dart Rifle",
		"Chain Guillotines",
		"Fetid Baghnakhs",
		"Clinger Staff",
		"Seedler",
		"Hellwing Bow",
		"Daedalus Stormbow",
		"Flying Knife",
		"Crystal Vile Shard",
		"Shadowflame Bow",
		"Shadowflame Hex Doll",
		"Shadowflame Knife",
		"Meowmere",
		"Star Wrath",
		"Wand of Sparking",
		"Butcher's Chainsaw",
		"Toxic Flask",
		"Psycho Knife",
		"Nail Gun",
		"Bouncy Grenade",
		"Crystal Serpent",
		"Toxikarp",
		"Bladetongue",
		"Bone Glove",
		"Deadly Sphere Staff",
		"Slap Hand",
		"Code 1",
		"Medusa Head",
		"Wooden Yoyo",
		"Malaise",
		"Artery",
		"Amazon",
		"Cascade",
		"Chik",
		"Code 2",
		"Rally",
		"Yelets",
		"Red's Throw",
		"Valkyrie Yoyo",
		"Amarok",
		"Hel-Fire",
		"Kraken",
		"The Eye of Cthulhu",
		"Format:C",
		"Gradient",
		"Valor",
		"Exotic Scimitar",
		"Paintball Gun",
		"Classy Cane",
		"Stylish Scissors",
		"Arkhalis",
		"Amber Staff",
		"Terrarian",
		"Stardust Pickaxe",
		"Solar Eruption",
		"Stardust Cell Staff",
		"Vortex Beater",
		"Nebula Arcanum",
		"Solar Flare Hamaxe",
		"Vortex Hamaxe",
		"Nebula Hamaxe",
		"Stardust Hamaxe",
		"Stardust Dragon Staff",
		"Phantasm",
		"Last Prism",
		"Nebula Blaze",
		"Daybreak",
		"Celebration",
		"Happy Grenade",
		"Lunar Portal Staff",
		"Lunar Flare",
		"Rainbow Crystal Staff"
	)
	"1" => array(
		"Copper Bow",
		"Copper Hammer",
		"Copper Axe",
		"Copper Shortsword",
		"Copper Broadsword",
		"Copper Pickaxe",
		"Silver Bow",
		"Silver Hammer",
		"Silver Axe",
		"Silver Shortsword",
		"Silver Broadsword",
		"Silver Pickaxe",
		"Gold Bow",
		"Gold Hammer",
		"Gold Axe",
		"Gold Shortsword",
		"Gold Broadsword",
		"Gold Pickaxe",
		"Iron Pickaxe",
		"Iron Broadsword",
		"Iron Shortsword",
		"Iron Hammer",
		"Iron Axe",
		"Wooden Sword",
		"Wooden Bow",
		"Platinum Bow",
		"Platinum Hammer",
		"Platinum Axe",
		"Platinum Shortsword",
		"Platinum Broadsword",
		"Platinum Pickaxe",
		"Tungsten Bow",
		"Tungsten Hammer",
		"Tungsten Axe",
		"Tungsten Shortsword",
		"Tungsten Broadsword",
		"Tungsten Pickaxe",
		"Lead Bow",
		"Lead Hammer",
		"Lead Axe",
		"Lead Shortsword",
		"Lead Broadsword",
		"Lead Pickaxe",
		"Tin Bow",
		"Tin Hammer",
		"Tin Axe",
		"Tin Shortsword",
		"Tin Broadsword",
		"Tin Pickaxe",
		"Cactus Sword",
		"Cactus Pickaxe",
		"Shadewood Sword",
		"Shadewood Hammer",
		"Shadewood Bow",
		"Ebonwood Sword",
		"Ebonwood Hammer",
		"Ebonwood Bow",
		"Rich Mahogany Sword",
		"Rich Mahogany Hammer",
		"Rich Mahogany Bow",
		"Pearlwood Sword",
		"Pearlwood Hammer",
		"Pearlwood Bow",
		"Spear",
		"Blowpipe",
		"Wooden Boomerang",
		"Grenade",
		"Palm Wood Bow",
		"Palm Wood Hammer",
		"Palm Wood Sword",
		
	),
	"2" => array(
	
	),
	"3" => array(
	
	),
	"4" => array(
	
	),
	"5" => array(
	
	),
	"6" => array(
	
	),
);

//$tier = rand(1,6);
$tier = '1';

echo $sender.' you must kill '.$BOSS_LIST['1'][array_rand($BOSS_LIST['1'])].' using The '.$WEAPON_LIST['1'][array_rand($WEAPON_LIST['1'])];
?>
